version: '3'
services:
  api:
    build: ./backend/
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/api
    ports:
      - 3001:3000
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    env_file:
      - .env

  bot:
    env_file:
      - .env
    build: ./backend/
    command: ruby bot.rb
    volumes:
      - ./backend:/api
    depends_on:
      - api